### CREATE five documents.
POST http://localhost:3000/timesheets HTTP/1.1
content-type: application/json

{
    "date": "03-03-2024",
    "timeSpent": 201,
    "subject": "Web Development"
}


### CREATE 2
POST http://localhost:3000/timesheets HTTP/1.1
content-type: application/json

{
    "date": "03-03-2024",
    "timeSpent": 200,
    "subject": "Data Structures"
}

### CREATE 3
POST http://localhost:3000/timesheets HTTP/1.1
content-type: application/json

{
    "date": "03-02-2024",
    "timeSpent": 190,
    "subject": "Data Structures"
}

### CREATE 4
POST http://localhost:3000/timesheets HTTP/1.1
content-type: application/json

{
    "date": "03-03-2024",
    "timeSpent": 160,
    "subject": "Web Development"
}

### CREATE 5
POST http://localhost:3000/timesheets HTTP/1.1
content-type: application/json

{
    "date": "03-01-2024",
    "timeSpent": 120,
    "subject": "Web Development"
}


### RETRIEVE all documents.
GET http://localhost:3000/timesheets HTTP/1.1



### RETRIEVE a document by its ID.
### Replace the following ID with one that exists in the collection.
GET http://localhost:3000/timesheets/65e54548ccbd0adaeda57fc3 HTTP/1.1


### UPDATE one document's time, by ID.
### Replace the ID in the following request with one that exists
### and update the time:
PUT http://localhost:3000/timesheets/65e53df4f493d4ffe0a0e20f HTTP/1.1
content-type: application/json

{
    "date": "2024-03-03",
    "timeSpent": 201,
    "subject": "Web Development"
}

### DELETE by ID (responds with nothing if successful):
DELETE http://localhost:3000/timesheets/65e5420f3fdc33b4157b323c HTTP/1.1



### RETRIEVE all documents (responds with 4 or the original 5):
GET http://localhost:3000/timesheets HTTP/1.1

